server:
  port: ${SERVER_LOCAL_PORT}
  servlet:
    session:
      timeout: 300s

spring:
  application:
    name: web-final-project

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
logging:
  level:
    org:
      springframework:
        security: INFO
application:
  admin:
    default:
      username: ${ADMIN_DEFAULT_USERNAME}
      password: ${ADMIN_DEFAULT_PASSWORD}
      email: ${ADMIN_DEFAULT_EMAIL}