server:
  port: ${SERVER_LOCAL_PORT}
  servlet:
    session:
      timeout: 300s

spring:
  application:
    name: web-final-project

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVER}
    password: ${PASSWORD_EMAIL_SERVER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        security: INFO
application:
  admin:
    default:
      username: ${ADMIN_DEFAULT_USERNAME}
      password: ${ADMIN_DEFAULT_PASSWORD}
      email: ${ADMIN_DEFAULT_EMAIL}