name: Web final project

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run maven checkstyle
        run: mvn checkstyle:checkstyle

  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile project
        run: mvn clean compile

  build:
    runs-on: ubuntu-latest
    name: Build project
    needs: [compile]  # Build sẽ chạy sau compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Building project
        run: mvn package

  check:
    runs-on: ubuntu-latest
    name: Git-leaks check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Gitleaks binary
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: |
          gitleaks detect --source="." --config="./gitleaks.toml" --verbose --no-git